# Generated by Django 5.2.5 on 2025-09-07 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbook",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_books",
                to="livros.livro",
            ),
        ),
        migrations.AddField(
            model_name="userbook",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="livros",
            field=models.ManyToManyField(
                blank=True,
                related_name="leitores",
                through="contas.UserBook",
                through_fields=("usuario", "livro"),
                to="livros.livro",
            ),
        ),
        migrations.AddField(
            model_name="userbookmonthlygoal",
            name="user_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metas_mensais",
                to="contas.userbook",
            ),
        ),
        migrations.AddIndex(
            model_name="userbook",
            index=models.Index(
                fields=["usuario", "livro"], name="contas_user_usuario_8b6c71_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbook",
            unique_together={("usuario", "livro")},
        ),
        migrations.AddIndex(
            model_name="userbookmonthlygoal",
            index=models.Index(
                fields=["user_book", "mes"], name="contas_user_user_bo_dd160f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbookmonthlygoal",
            unique_together={("user_book", "mes")},
        ),
    ]
