# Generated by Django 5.2.5 on 2025-08-26 22:34

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_usuario_managers_usuario_access_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="access_key",
            field=models.CharField(
                db_index=True,
                default=contas.models.generate_access_key,
                editable=False,
                help_text="Chave fixa de 32 caracteres para autenticação por header.",
                max_length=32,
                unique=True,
            ),
        ),
    ]
