# Generated by Django 5.2.5 on 2025-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="meta_mensal_paginas",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Meta mensal padrão. Se vazio, usa meta_anual_paginas/12.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="UserBookMonthlyGoal",
        ),
    ]
