# Generated by Django 5.2.5 on 2025-09-07 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("total_paginas", models.PositiveIntegerField()),
                (
                    "avaliacao",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Péssimo"),
                            (2, "Ruim"),
                            (3, "Regular"),
                            (4, "Bom"),
                            (5, "Ótimo"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "capa_url",
                    models.URLField(blank=True, null=True, verbose_name="URL Imagem"),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                (
                    "google_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="livros.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeituraDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("paginas_lidas", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="livros.livro",
                    ),
                ),
            ],
            options={
                "ordering": ["-dia"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "livro", "dia"),
                        name="unique_leitura_por_usuario_livro_dia",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("paginas_lidas__gt", 0)),
                        name="leit_diaria_paginas_gt_zero",
                    ),
                ],
            },
        ),
    ]
