# Generated by Django 5.2.5 on 2025-09-04 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("pag_atual", models.PositiveIntegerField(default=0)),
                ("total_paginas", models.PositiveIntegerField()),
                (
                    "avaliacao",
                    models.IntegerField(
                        choices=[
                            (1, "Péssimo"),
                            (2, "Ruim"),
                            (3, "Regular"),
                            (4, "Bom"),
                            (5, "Ótimo"),
                        ],
                        default=3,
                        null=True,
                    ),
                ),
                ("capa_url", models.URLField(blank=True, verbose_name="URL Imagem")),
                ("isbn", models.CharField(blank=True, max_length=32)),
                ("google_id", models.CharField(blank=True, max_length=32)),
                ("data_inicio", models.DateField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="livros.categoria",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="leituradiaria",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leituras",
                to="livros.livro",
            ),
        ),
        migrations.DeleteModel(
            name="Livros",
        ),
    ]
