# Generated by Django 5.2.5 on 2025-09-09 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leituradiaria",
            name="paginas_lidas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="leituradiaria",
            index=models.Index(
                fields=["usuario", "dia"], name="livros_leit_usuario_dce240_idx"
            ),
        ),
    ]
