# Generated by Django 5.2.5 on 2025-09-12 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_alter_leituradiaria_paginas_lidas_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="leituradiaria",
            name="leit_diaria_paginas_gt_zero",
        ),
        migrations.AddConstraint(
            model_name="leituradiaria",
            constraint=models.CheckConstraint(
                condition=models.Q(("paginas_lidas__gte", 0)),
                name="leit_diaria_paginas_gte_zero",
            ),
        ),
    ]
