# Generated by Django 5.2.5 on 2025-09-04 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_categoria_livro_alter_leituradiaria_livro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="livros.categoria",
            ),
        ),
    ]
