# Generated by Django 5.2.5 on 2025-09-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_alter_livro_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="avaliacao",
            field=models.IntegerField(
                choices=[
                    (1, "Péssimo"),
                    (2, "Ruim"),
                    (3, "Regular"),
                    (4, "Bom"),
                    (5, "Ótimo"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="capa_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL Imagem"),
        ),
    ]
