# Generated by Django 5.2.5 on 2025-09-14 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_remove_leituradiaria_leit_diaria_paginas_gt_zero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="livros.categoria",
            ),
        ),
    ]
