# Generated by Django 5.2.5 on 2025-09-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0004_alter_livro_avaliacao_alter_livro_capa_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="google_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
