# Generated by Django 5.2.5 on 2025-09-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0005_alter_livro_google_id_alter_livro_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="google_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
